Projects/App/SYM.xcodeproj/project.pbxproj, Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift, Projects/App/Sources/DesignSystem/Color/Color.swift, Projects/App/Sources/DesignSystem/Font/Font.swift, Projects/App/Sources/DesignSystem/Font/FontDemo.swift, Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj, SYM.xcworkspace/contents.xcworkspacedata, Tuist/Dependencies.swift
* 디자인 시스템 예제를 참고해서 Font와 Color를 정의했습니다.
* 예제의 DesignSystem 구조체를 놔두고 Color, Font 파일에서 extension으로 진행했습니다.
* extension, viewmodifier 다 만들어져 있습니다
=> feat: Font, Color 디자인 시스템 추가

Projects/App/SYM.xcodeproj/project.pbxproj, Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift, Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj, SYM.xcworkspace/contents.xcworkspacedata
- Default Button, Disabled Button 생성 완료 했습니다.
- Pressed Button의 경우 디자인상 Default와 차이가 없어서 지수님과 협의 후에 다시 고치겠습니다 (현재는 pressed시에 opacity가 변경되게 해두었습니다.)
- 더 좋은 컴포넌트 방식이 있다면 마구마구 코멘트 부탁드립니다!
=> feat: Button 컴포넌트 생성

Projects/App/SYM.xcodeproj/project.pbxproj, Projects/App/Sources/DesignSystem/Button/Button.swift, Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift, Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift, Projects/App/Sources/DesignSystem/Form/FormDemo.swift, Projects/App/Sources/DesignSystem/Form/TextEditor.swift, Projects/App/Sources/DesignSystem/Form/TextField.swift, Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj, SYM.xcworkspace/contents.xcworkspacedata
- TextField, TextEditor 관련 컴포넌트 구현 완료했습니다.
- 그 외에 편리하게 사용하기 위해서 팝업 컴포넌트에 docs(///) 추가해 놓았어요.
- 버튼 컴포넌트 파일 분리했습니다. (구현 부분(Button)과 데모 부분(ButtonDemo)
- 색상과 폰트크기 모두 적용해 놓았습니다.
어떤 변경 사항이 있나요?
<br>
색상이랑 폰트 다 적용해 놓았는데요..
혹시 안 되어 있는곳을 발견하시면 말씀주세용
=> feat, refactor: TextField, TextEditor 관련 컴포넌트 구현과 버튼 컴포넌트 파일 분리

Projects/App/Sources/Presentation/MainView.swift
- 본격적인 뷰 구성에 앞서 탭바 구현 완료 했습니다. 
- 각자 Presentation 폴더링 밑에 있는 폴더에서 View, ViewModel 작업해주시면 됩니다.
- 저희 폰트가 커스텀으로 들어가서 탭바도 커스텀으로 구현할 수 밖에 없었어요 😢
- enum으로 first, second, third 로 분기하여 각 뷰 구현해 놓았습니다.
- 배경은 .white, foreground (symgray3, symblack으로 분기처리)
어떤 변경 사항이 있나요?
<br>
혹시 더 좋은 방법있으면 말씀주세요! 수정해주셔도 좋아요.
=> feat: 커스텀 탭바 구현

Projects/App/Sources/DesignSystem/Color/Color.swift, Projects/App/Sources/DesignSystem/Common/BackgroundColor.swift, Projects/App/Sources/DesignSystem/CustomAlert/PopupViewDemo.swift, Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift, Projects/App/Sources/DesignSystem/Font/Font.swift, Projects/App/Sources/DesignSystem/Font/FontDemo.swift, Projects/App/Sources/DesignSystem/Form/FormDemo.swift, Projects/App/Sources/DesignSystem/Form/TextEditor.swift, Projects/App/Sources/DesignSystem/Form/TextField.swift, Projects/App/Sources/Presentation/Sign/View/SignupNicknameView.swift, Projects/App/Sources/Presentation/Sign/View/SignupView.swift
- 컴포넌트 수정 사항 반영
- Extension Font 레거시 코드 삭제
<br>
<br>
<br>
- 팝업 뷰 관련 수정사항 모두 반영하였습니다.
<br>
<br>
- 혜연님께서 기록 관련 글자 수 200자 한도로 하시는거 미리 말씀 주셔서 일단 적용시켜놓았습니다.
<br>
<br>
<br>
<br>
<br>
- 해당 부분에서 사용되는 색상 추가해 놓았습니다.
어떤 변경 사항이 있나요?
<br>
<br>
- 닉네임 관련 글자수 확인 및 문구 관련해서 코드 enum으로 나눠서 리팩토링 해놓았습니다.
- 추후에 관련 문구 수정해야 하면 NicknameRule enum 수정 부탁드려요!
- 현재 말풍선 색상 우선 파란색으로 설정해 놓았어요. 우선 bubble로 그리고 색상 값 픽스되면 그때 extension에서 바뀌면 될것 같습니다.
- 현재 피그마에 적용되어 있는 글자 크기로 가이드라인 팝업뷰 제작시 글자가 커서.. 저렇게 깨지는데 small로 낮추는게 낫겠죠?
=> feat, refactor: Form, Popup 컴포넌트 수정, SignUpNicknameView 리팩토링

Projects/App/Sources/DesignSystem/Button/Button.swift, Projects/App/Sources/DesignSystem/Color/Color.swift, Tuist/Dependencies.swift
- button frame, padding, cornerRadius 변경했습니다.
- 활성화 된 버튼이 눌렸을 때 색이 짙어지도록 디자인 시스템 변경되어 Color 추가(Color.symPressedPink) 후에 버튼 pressed 시에 background 색 변경되도록 했습니다.
`.background(configuration.isPressed ? Color.symPressedPink : Color.symPink)`
+) 추가로 tuist firebase 관련 dependency 변경했습니다.
<br>
https://github.com/Good-MoGong/SYM/assets/133854561/184e4e58-5312-472f-a3ba-bf19ef82f4c9
- 버튼 눌렸을때 사용되는 짙은 핑크가 여기에만 사용될 것 같아서 네이밍을 `symPressedPink` 라고 지었는데 혹시 더 좋은 네이밍 의견이 있거나  다른 곳에서도 이 색상이 쓰인다면 이름 변경하겠습니다.
=> Feat: button 컴포넌트 수정

Projects/App/Sources/DesignSystem/Button/Button.swift, Projects/App/Sources/DesignSystem/ChatBubble/ChatBubble.swift, Projects/App/Sources/DesignSystem/Color/Color.swift, Projects/App/Sources/DesignSystem/Color/ColorDemo.swift, Projects/App/Sources/DesignSystem/Common/BackgroundColor.swift, Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift, Projects/App/Sources/DesignSystem/Form/TextField.swift, Projects/App/Sources/Presentation/Sign/View/SignupNicknameView.swift, Projects/App/Sources/Presentation/Tab/MainTab.swift, Projects/App/Sources/Presentation/Tab/MainView.swift, Projects/App/Sources/Presentation/Tab/TestTabView.swift
- 색상 컴포넌트 값 수정된 사항 반영 완료 했습니다.
- 컴포넌트 이름은 피그마에 적혀져있는 이름으로 모두 변경하였고, 현재 작성되어 있던 색상 값 코드에도 모두 반영해놓았습니다.
- 탭바 커스텀 디자인은 수정 중이며 일단은 뷰작업 진행하고 나중에 연결해도 될것 같습니다.. (코드 무시해주세용~)
<br>
<br>
변경된 색상 컴포넌트 변수명 확인 부탁드려요!
=> feat: 색상 컴포넌트 수정

Projects/App/Sources/DesignSystem/Button/Button.swift, Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift, Projects/App/Sources/DesignSystem/Color/Color.swift, Projects/App/Sources/Presentation/Tab/TestTabView.swift
- 디자인 시스템 변경에 따른 `Color 컴포넌트` 수정 했습니다
- `Main Button`, `Disabled Button` : foreground, backgroundColor 수정 했습니다.
- `SubPinkButtonStyle` 추가 : 마이페이지에서 사용되는 "시미에게 의견 보내기" 버튼에 사용될 `sub color` 이용한 버튼 생성했습니다.
=> 디자이너님과 협의 결과 해당 버튼의 vertical padding 값 조정 필요해서 기존 19에서 10으로 조정했습니다
- `smallGrayButtonStyle` 추가 : 감정기록 완료 후에 "홈" 버튼에 사용될 gray 버튼 생성했습니다.
=> 디자이너님과 협의 결과 해당 버튼이 disabled button과 유사하나 "홈" 버튼과 함께 쓰일 "기록 보기" 버튼에 더 초점이 갈 수 있도록 하기 위해서 이렇게 구현하기로 했습니다.
- 디자인 시스템 변경에 의해 button pressed 시 색이 더 짙어지는 구현은 하지 않기로 하여 삭제했습니다.
- `SubPinkButtonStyle`
- `smallGrayButtonStyle` : 왼쪽 버튼
- 현재까지의 기능 및 최종 와이어프레임 상에서 `SubPinkButtonStyle`와 `smallGrayButtonStyle`이 아주 특정 부분에만 사용되어 해당되는 특정 부분에 맞춰 구현했습니다. 추후 기능 및 UI 확장시에 더 사용될 가능성이 있을 경우 세부 사항 조정하겠습니다.
- 더 나은 네이밍이 있다면 ,, 추천 마구마구 부탁드립니다 ,,
=> Feat, Refact: Color 컴포넌트 수정 및 Button 컴포넌트 수정

.gitignore
=> feat: 프로비저닝 설정 완료 및 gitignore 수정

Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
- 뒷배경 보이도록 팝업 컴포넌트 수정 완료
- 뚝뚝 끊기지 않도록 애니메이션 추가했습니다.
<br>
https://github.com/Good-MoGong/SYM/assets/110394722/cd18e768-699e-4ad4-96b3-3622c9acd923
<br>
=> fix, feat: popup 컴포넌트 수정 및 애니메이션 추가

Projects/App/Sources/Presentation/Record/RecordOrganizeView.swift
- 기록 보기 뷰에서 아이폰 해상도 별 Padding 조절 함수 수정했습니다
- if문을 Group으로 묶었습니다.
어떤 변경 사항이 있나요?
=> fix: 기록 보기 뷰에서 아이폰 해상도 별 Padding 조절 함수 수정

Projects/App/Project.swift, Projects/FirebaseSPM/Project.swift, Tuist/Dependencies.swift, Tuist/ProjectDescriptionHelpers/Project+Templates.swift, Tuist/ProjectDescriptionHelpers/SPM+Dependencies.swift, Tuist/ProjectDescriptionHelpers/Target+Templates.swift
- Tuist 관련 기존 의존 방식 Tuist SPM에서 Xocde SPM으로 변경하였습니다.
- objc 관련 warning이 많아서 변경했어요.
- 이슈 페이지에 있는 참고 링크 확인부탁드려요.
<br>
=> refactor: Tuist 의존성 방식 Xcode SPM으로 변경

Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift, Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift, Projects/App/Sources/Presentation/Tab/MainView.swift
- .blendMode로 디자인 수정완료했습니다.
<br>
중간에 textfield 수정 사항은 특수문수 처리 관련해서 진행 중이었는데, 해당 기능은 로그인 구현 완료되면 마저 브랜치 새로 파서 작업할게요!
=> fix: 애플 로그인 버튼 디자인 수정

Projects/App/Sources/DesignSystem/Toast/Toast.swift, Projects/App/Sources/DesignSystem/Toast/ToastModifier.swift, Projects/App/Sources/DesignSystem/Toast/ToastView.swift, Projects/App/Sources/Presentation/Record/RecordStartView.swift, Projects/App/Sources/Presentation/Record/RecordViewModel.swift
토스트뷰 컴포넌트 구현했습니다
사용방법: 뷰 최상단에 .toastView(toast: Binding<Toast>) modifier로 달아주세요~
ex)
#77 
어떤 변경 사항이 있나요?
https://github.com/Good-MoGong/SYM/assets/127810279/dbdceed1-b996-46d3-abf7-3a14f582525d
Toast case 더 필요하시면 말씀해주세요~
=> Feat: 토스트뷰 컴포넌트 구현

Projects/App/Sources/Extensions/KeyPathExtension.swift, Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift, Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift, Tuist/ProjectDescriptionHelpers/Target+Templates.swift
- CalendeView에서 사용하는 Picker 제작 완료했습니다.
- iOS 호환성 이슈가 발견되어서 문제가 되는 KeyPathExtension 코드를 변경했습니다.
- Tuist의 iOS 버전을 16.4로 변경하였습니다.
어떤 변경 사항이 있나요?
https://github.com/Good-MoGong/SYM/assets/66257281/15e0fe9c-4154-4bc1-a573-6a22ea9420fc
=> Feat, Fix, Docs: CustomDatePicker 구현, KeyPathExtension 호환성 개선, Tuist iOS 버전 변경(16.4)

Projects/App/Project.swift, Projects/FirebaseSPM/Project.swift
어떤 변경 사항이 있나요?
- Tusit 버전 정보 반영 다 안 돼서 제가 수정해서 머지할게요~
- 16.0 -> 16.4 로만 수정해놓아서 hotFix, 관리자 권한 머지하겠습니다.
<br>
=> hotFix: Tusit 버전 미반영 부분 수정

Projects/App/Sources/DesignSystem/CustomAlert/CommonDoubleBtnView.swift, Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordEnum.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordUseCase.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordViewModel.swift, Projects/App/Sources/Presentation/Record/Views/RecordDemo.swift, Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift, Projects/App/Sources/SYMApp.swift
기록하기 Guide팝업 생성
1. PopupView Spacer간격 spacing으로 변경했습니다.
2. PopupView @State 프로퍼티들 let으로 변경했습니다.
- 값을 넘겨받는데 @State로 선언돼있어 외부에서 넘어오는 값이 바뀔때마다 바뀌지 않았습니다.
let, var는 stack메모리에 저장되어 넘어오는 값이 바뀔때마다 메모리도 해제됐다 다시 저장되고, 
@State는 heap메모리에 저장되어 뷰의 수명 주기 동안 유지되며, 해당 뷰가 제거되면 메모리에서 해제됩니다.
(recordStartView에서 enum으로 뷰가 바뀌기 때문에 @State는 해제안됨) 
- PopupVIew내부에서 @State로 값이 변경되는 케이스는 보이지 않아 바꿨습니다.
3. animation deprecated 코드 변경했습니다.
어떤 변경 사항이 있나요?
https://github.com/Good-MoGong/SYM/assets/127810279/63ed7ef2-cfab-43c6-950d-455554140593
화이팅~~!!
=> Feat: 기록하기 Guide팝업 생성

Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift, Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift
- Calender를 좌우로 드래그해서 Month를 바꿀 때 Picker의 동작 조건과 맞춰서 현재 Month 이상과 2024년 1월 미만으로는 움직일 수 없도록 했습니다.
어떤 변경 사항이 있나요?
=> Feat: CalenderView Gesture 이동 제한 조건 설정과 Picker 이동과의 상태 연동

Projects/App/Sources/DesignSystem/Common/RecordView.swift, Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift, Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift, Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift, Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift, Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift, Projects/App/Sources/Presentation/MyPage/MypageView.swift
- AuthenticationViewModel에 @AppStorage(UserDefaults)로 로컬에 닉네임을 저장해서 사용하도록 했습니다.
- 닉네임이 사용되는 View에서 닉네임이 변경 되었을 때 View에 반영되도록 했습니다.
- 닉네임을 변경하고 완료 버튼을 누르면 뒤로가기가 되도록 했습니다.
어떤 변경 사항이 있나요?
https://github.com/Good-MoGong/SYM/assets/66257281/15113260-8735-4655-b6ae-3cb90a423cc7
=> Refact: 닉네임이 사용되는 View에서 닉네임이 변경 되었을 때 반영, 닉네임 변경 후 완료 버튼 누르면 dismiss

Projects/App/Resources/GoogleService-Info.plist, Projects/App/Sources/DesignSystem/Form/TextEditor.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordRepository.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordUseCase.swift, Projects/App/Sources/Presentation/Record/Architectures/RecordViewModel.swift, Projects/App/Sources/Presentation/Record/Views/RecordOrganizeView.swift, Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift
|기존|변경|
|:---:|:---:|
|<img width="250" alt="스크린샷 2024-03-05 오후 3 47 14" src="https://github.com/Good-MoGong/SYM/assets/127810279/4ecf616a-38a3-4f63-883e-77b2267171ef">|<img width="250" alt="스크린샷 2024-03-05 오후 3 47 40" src="https://github.com/Good-MoGong/SYM/assets/127810279/b315dec0-ccc6-40dc-b2ac-ea646507db89">|
|기존 **ZStack, overlay**는 뷰 위에 뷰를 쌓는 방식입니다.<br>따라서 TextEditor가 맨 아래로 가고 그 위에 Text(placeholder)가 쌓이게 됩니다.<br>결과적으로 위에 쌓인 Text영역을 누르게 되고 TextEditor가 반응하지 못합니다.<br>실제 Text영역을 피해 누르면 키보드가 올라옵니다. |변경한 코드는 **background**로 TextEditor 아래에 Text(placeholder) 보여주는 방식입니다.<br>이렇게 하면 결과적으로  TextEditor를 누르게 되어 키보드가 올라옵니다.<br>글자수Text는 위에 쌓아도 상관없다 생각해서 overlay로 했습니다.|
ps. 키보드 time out 해결
프리뷰나 시뮬에서 TextField나 TextEditor를 누르면 
에러가 뜨면서 락이 걸려 불편했었다.. 이유는 바로 수정제안자 때문이다 
1. …
=> Refactor: TextEditor 안눌림 해결 + 키보드 time out 해결, gpt응답메시지 Completion -> Combine으로 리팩토링, 기록보기 뷰 뒤로가기 제스처 기능 
